<#
    Every sentence Housecall shows, in English and Dutch.

    Nothing user-facing is hard-coded anywhere else: code asks for a key with
    T 'some.key' and gets the current language. Both tables must have exactly
    the same keys -- tests/Housecall.Tests.ps1 fails when they drift.

    Dutch uses the formal "u": the person reading over your shoulder is often
    an older client.

    Keep this file plain ASCII. PowerShell 5.1 reads a .ps1 without a
    byte-order mark as ANSI, so an accented letter here would turn to mojibake.
#>

$script:Strings = @{
    en = @{
        'tagline'          = 'finds and fixes computer problems, always with your okay'
        'promise'          = 'Nothing changes on this PC without a yes.'

        'status.admin'     = 'admin'
        'status.notAdmin'  = 'not admin'
        'status.online'    = 'online'
        'status.offline'   = 'offline'
        'status.dryRun'    = 'DRY RUN: checks only, nothing gets fixed'

        'menu.question'    = 'What is the problem about?'
        'menu.ai'          = 'Something else: describe it yourself (AI chat)'
        'menu.hintHome'    = 'Type a letter, or jump straight to a problem, e.g. A1'
        'menu.back'        = 'Back'
        'menu.language'    = 'Nederlands'
        'menu.quit'        = 'Quit'
        'menu.prompt'      = 'Choose'
        'menu.unknown'     = '"{0}" is not an option. Try a letter such as A, or a code such as A1.'

        'area.question'    = '{0}  {1}: what is the problem?'
        'area.ai'          = 'None of these: describe it yourself (AI chat)'
        'area.hint'        = 'Type a number, e.g. 1, or the full code'

        'problem.notBuilt' = 'The checks for this problem are not built yet.'
        'problem.willLook' = 'It will look at:'
        'pressEnter'       = 'Press Enter to go back'

        'ai.title'         = 'Describe the problem in your own words'
        'ai.youTyped'      = 'You typed: {0}'
        'ai.notBuilt'      = 'The AI chat is not built yet. Choose a letter from the menu for now.'
        'ai.offline'       = 'This PC is offline, so the AI chat cannot be reached. The menu works without internet.'

        'goodbye'          = 'Housecall is closed. Nothing was left behind on this PC.'
        'goodbyeChanged'   = 'Housecall is closed. The {0} change(s) you approved stay in place; nothing else was left behind.'
        'env.notWindows'   = 'Housecall only runs on Windows.'
        'env.oldPowerShell' = 'Housecall needs PowerShell 5.1 or newer. This PC has {0}.'

        'area.A'  = 'Internet & Wi-Fi'
        'area.B'  = 'Sound, screen & video calls'
        'area.C'  = 'Printer & devices'
        'area.D'  = 'Slow or freezing'
        'area.E'  = 'Windows & updates'
        'area.F'  = 'Safety & scams'

        'looks.A' = 'network adapter, address from the router, router, DNS, internet, proxy, Wi-Fi signal'
        'looks.B' = 'default sound device, mute and volume, audio service, camera and microphone access, screen scale'
        'looks.C' = 'print service, stuck print jobs, default printer, USB devices with errors, Bluetooth'
        'looks.D' = 'free disk space, programs using memory and CPU, startup programs, recent crashes, time since restart'
        'looks.E' = 'Windows Update service, last successful update, waiting restart'
        'looks.F' = 'remote-access programs such as AnyDesk, sites allowed to send pop-ups, Microsoft Defender, unknown scheduled tasks'

        'problem.A1' = 'No internet at all'
        'problem.A2' = 'Wi-Fi slow or keeps dropping'
        'problem.A3' = 'One website or app will not load'
        'problem.A4' = 'Email will not send or arrive'
        'problem.B1' = 'No sound'
        'problem.B2' = 'Microphone or camera (video calls)'
        'problem.B3' = 'Screen too small, too dark or wrong'
        'problem.C1' = 'Printer will not print'
        'problem.C2' = 'Mouse, keyboard or USB stick'
        'problem.C3' = 'Bluetooth'
        'problem.D1' = 'The whole computer is slow'
        'problem.D2' = 'Takes ages to start'
        'problem.D3' = 'A program freezes or crashes'
        'problem.D4' = 'The disk is full'
        'problem.E1' = 'Update stuck or failing'
        'problem.E2' = 'Error message on the screen'
        'problem.E3' = 'Will not shut down or restart'
        'problem.F1' = 'A pop-up says I have a virus'
        'problem.F2' = 'Someone called me and got into my computer'
        'problem.F3' = 'Full security check'

        # ---- running a check
        'run.checking' = 'Checking... nothing changes on this PC.'
        'run.found'    = 'Found:'
        'run.advice'   = 'What to do:'

        # ---- A: check lines
        'net.noAdapter'        = 'No network adapter found'
        'net.wifiDisabled'     = 'Wi-Fi adapter "{0}" is switched off'
        'net.adapterOff'       = 'Network adapter "{0}" is switched off'
        'net.wifiNotConnected' = 'Wi-Fi is on, but not connected to any network'
        'net.cableUnplugged'   = 'No network cable plugged in ("{0}")'
        'net.adapterUp'        = 'Network adapter "{0}" is on'
        'net.wifiConnected'    = 'Connected to Wi-Fi "{0}", signal {1}%'
        'net.wifiConnectedNoSignal' = 'Connected to Wi-Fi'
        'net.cableConnected'   = 'Connected by network cable'
        'net.weakSignal'       = 'The Wi-Fi signal is weak: {0}%'
        'net.proxy'            = 'Traffic goes through a proxy: {0}'
        'net.noAddress'        = 'No address from the router ({0})'
        'net.address'          = 'Address from the router: {0}'
        'net.addressStatic'    = 'Fixed address, set by hand: {0}'
        'net.noGateway'        = 'No router (gateway) set for this connection'
        'net.gatewayOk'        = 'Router {0} answers in {1} ms'
        'net.gatewayNoPing'    = 'Router {0} ignores test messages (that is fine)'
        'net.gatewayDown'      = 'Router {0} does not answer'
        'net.internetDown'     = 'Nothing gets past the router to the internet'
        'net.internetOk'       = 'Internet reachable, {0} ms'
        'net.dnsDown'          = 'Website names are not found (DNS server {0})'
        'net.dnsOk'            = 'Website names are found (DNS)'
        'net.webOk'            = 'Test page loads normally'
        'net.webIntercepted'   = 'A login page or another program catches web traffic'
        'net.webFailed'        = 'The test page does not load'
        'net.skipped'          = 'Remaining checks skipped'
        'net.lossOk'           = 'Router test: all {0} messages came back, {1} ms on average'
        'net.loss'             = 'Router test: {0} of {1} messages got lost'
        'net.drops'            = 'Wi-Fi disconnects in the past 7 days: {0} (sleep and shutdown included)'
        'net.internetWorks'    = 'The internet works on this PC'
        'net.none'             = 'none'

        # ---- A: findings, and what to do about each
        'finding.noAdapter'        = 'Windows sees no network adapter at all. The driver may be missing, or the adapter is broken.'
        'advice.noAdapter'         = 'Open Device Manager and look for a network adapter with a warning sign. Install the driver from the maker''s website, using a phone (USB tethering) or another PC.'
        'finding.wifiDisabled'     = 'The Wi-Fi adapter is switched off.'
        'advice.wifiDisabled'      = 'Turn Wi-Fi on: Settings > Network & internet > Wi-Fi, or the Wi-Fi key on the keyboard. Also check that airplane mode is off.'
        'finding.adapterOff'       = 'The network adapter is switched off.'
        'advice.adapterOff'        = 'Turn it on again: Settings > Network & internet > Advanced network settings > Enable.'
        'finding.wifiNotConnected' = 'Wi-Fi is on, but the PC is not connected to a network.'
        'advice.wifiNotConnected'  = 'Check that airplane mode is off. Then click the Wi-Fi icon at the bottom right and choose the home network. The password is often on a sticker on the router.'
        'finding.cableUnplugged'   = 'This PC uses a network cable, but the cable is not connected.'
        'advice.cableUnplugged'    = 'Push the cable in at both ends until it clicks. Try another port on the router, or another cable.'
        'finding.noAddress'        = 'The PC is connected, but the router gave it no address.'
        'advice.noAddress'         = 'Renew the address: ipconfig /release, then ipconfig /renew. If that does not help, restart the router: power off for 30 seconds, then wait 3 minutes.'
        'finding.noGateway'        = 'No router is set for this connection. Usually a fixed address that was set by hand.'
        'advice.noGateway'         = 'Set the connection back to automatic: Settings > Network & internet > (the connection) > IP assignment > Automatic (DHCP).'
        'finding.gatewayDown'      = 'The router does not answer.'
        'advice.gatewayDown'       = 'Check that the router''s lights are on. Restart it: power off for 30 seconds, then wait 3 minutes.'
        'finding.internetDown'     = 'The router works, but the router itself has no internet.'
        'advice.internetDown'      = 'Restart the modem and router. Look for an outage at the provider, on a phone (e.g. allestoringen.nl). Check the internet light on the router.'
        'finding.dnsDown'          = 'The internet works, but website names are not found (DNS).'
        'advice.dnsDown'           = 'Clear the DNS cache: ipconfig /flushdns. If the DNS servers were set by hand, set them back to automatic.'
        'finding.webIntercepted'   = 'Something catches web traffic: a Wi-Fi login page (hotel, guest network) or a program on this PC.'
        'advice.webIntercepted'    = 'Open a browser and look for a login page. If there is none, run F3 to look for unknown programs.'
        'finding.proxy'            = 'A proxy is set. On a home PC that is usually unwanted, and sometimes adware.'
        'advice.proxy'             = 'Turn it off: Settings > Network & internet > Proxy. Then run F3 to look for unknown programs.'
        'finding.weakSignal'       = 'The internet works, but the Wi-Fi signal here is weak.'
        'advice.weakSignal'        = 'Move closer to the router, keep the router out of cupboards, or add a Wi-Fi extender or mesh point.'
        'finding.allGood'          = 'The internet connection works on this PC.'
        'advice.allGood'           = 'If one website or app fails, choose A3. If the internet is slow or drops, choose A2.'
        'finding.unstable'         = 'The connection to the router is unstable: {0}% of the test messages got lost.'
        'advice.unstable'          = 'Restart the router and move closer to it. A network cable is steadier than Wi-Fi.'
        'finding.dropsMany'        = 'Wi-Fi dropped {0} times in the past 7 days, more than sleep and shutdown explain.'
        'advice.dropsMany'         = 'Update the Wi-Fi driver, turn off power saving for the Wi-Fi adapter in Device Manager, and restart the router.'
        'finding.connHealthy'      = 'The connection looks healthy right now. Slowness probably comes from the subscription or the provider.'
        'advice.connHealthy'       = 'Run a speed test (e.g. speedtest.net) and compare it with the subscription. Try again at another time of day.'

        # ---- A3: one website
        'site.ask'       = 'Which website? For example: marktplaats.nl'
        'site.invalid'   = '"{0}" does not look like a web address. Type it like this: whatsapp.com'
        'site.hosts'     = 'The hosts file sends {0} to {1}'
        'site.hostsOk'   = 'No special rule for {0} in the hosts file'
        'site.dnsOk'     = '{0} found: {1}'
        'site.dnsFail'   = '{0} not found'
        'site.tcpOk'     = '{0} answers on the secure port, {1} ms'
        'site.tcpFail'   = '{0} does not answer on the secure port'
        'site.httpOk'    = '{0} sends a page (status {1})'
        'site.httpError' = '{0} answers with an error (status {1})'
        'site.httpNone'  = '{0} sends no page'

        'finding.siteHosts'    = 'The hosts file points this site to another address: an old setting, or malware.'
        'advice.siteHosts'     = 'Remove the line for this site from C:\Windows\System32\drivers\etc\hosts (needs admin), then run F3.'
        'finding.siteNotFound' = 'The name {0} is not found. It may be misspelled, or the site no longer exists.'
        'advice.siteNotFound'  = 'Check the spelling. Try it on a phone: if it fails there too, the problem is the site.'
        'finding.siteBlocked'  = 'The site is found, but it does not answer this PC.'
        'advice.siteBlocked'   = 'Try it on a phone with Wi-Fi off. If it works there, security software or a firewall on this PC may block it.'
        'finding.siteError'    = 'The site answers with an error ({0}). The problem is probably at the site itself.'
        'advice.siteError'     = 'Try again later. Check on a phone whether it fails there too.'
        'finding.siteOk'       = 'The site works from this PC. The problem is probably in the browser or the app.'
        'advice.siteOk'        = 'Clear the browser cache and cookies for this site, try another browser, or turn off browser extensions. For an app: update or reinstall it.'

        # ---- F: check lines
        'sec.noRemote'         = 'No remote-access programs found'
        'sec.installed'        = 'installed {0}'
        'sec.installedUnknown' = 'installed, date unknown'
        'sec.downloaded'       = 'downloaded {0}'
        'sec.running'          = 'RUNNING NOW'
        'sec.autoStart'        = 'starts with Windows'
        'sec.lastUsed'         = 'last used {0}'
        'sec.noTasks'          = 'No suspicious scheduled tasks'
        'sec.task'             = 'Scheduled task "{0}" runs: {1}'
        'sec.avUnknown'        = 'Could not read the virus protection status'
        'sec.avOff'            = 'No virus protection is switched on'
        'sec.avOld'            = '{0} is on, but last updated {1} days ago'
        'sec.avOutdated'       = '{0} is on, but out of date'
        'sec.avOk'             = '{0} is on and up to date'
        'sec.threats'          = 'Threats stopped in the past 30 days: {0}'
        'sec.notifyNone'       = 'No websites may send pop-up notifications'
        'sec.notifyKnown'      = 'Well-known sites may send notifications: {0}'
        'sec.notifySite'       = '{0} may send notifications ({1}, since {2})'
        'sec.notifySiteNoDate' = '{0} may send notifications ({1})'
        'sec.noProxy'          = 'No proxy set'
        'sec.hostsOk'          = 'The hosts file is normal'
        'sec.hostsRedirect'    = 'The hosts file redirects {0} name(s): {1}'

        # ---- F: findings, and what to do about each
        'finding.remoteActive'   = '{0} is running right now. Someone may be connected to this PC at this moment.'
        'advice.remoteActive'    = 'Cut the internet first: Wi-Fi off or pull the cable. Then close the program and ask the client whether they know it. If not: remove it after their yes, call the bank, and change the email and bank passwords from another device.'
        'finding.remoteRecent'   = '{0} was put on this PC recently ({1}). If the client did not do that themselves, it fits a tech-support scam.'
        'advice.remoteRecent'    = 'Ask the client who installed it. If it was a stranger: remove it after their yes, call the bank straight away, and change the email and bank passwords from another device.'
        'finding.remoteOld'      = '{0} has been on this PC for a while. Probably on purpose, but worth asking.'
        'advice.remoteOld'       = 'Ask the client whether they or their family use it. If nobody does, removing it closes a door.'
        'finding.defenderOff'    = 'Virus protection is switched off.'
        'advice.defenderOff'     = 'Turn it on: Windows Security > Virus & threat protection. If another antivirus has expired, remove it so Microsoft Defender takes over.'
        'finding.avOld'          = 'Virus protection is on, but not up to date.'
        'advice.avOld'           = 'Windows Security > Virus & threat protection > Protection updates > Check for updates. If that fails, choose E1.'
        'finding.threatsFound'   = 'Virus protection stopped {0} threat(s) in the past 30 days.'
        'advice.threatsFound'    = 'Open Windows Security > Protection history to see what it was, and run a full scan.'
        'finding.suspiciousTask' = 'The scheduled task "{0}" starts a hidden or downloaded command. That is typical of malware.'
        'advice.suspiciousTask'  = 'After the client''s yes, Housecall can disable it below (it can be switched back on). Then run a full scan in Windows Security.'
        'finding.unknownTask'    = 'The scheduled task "{0}" starts a script in the background. Legitimate programs do this too, but so does malware.'
        'advice.unknownTask'     = 'Ask the client whether they know it. If not, Housecall can disable it below (it can be switched back on).'
        'finding.notifySites'    = '{0} website(s) may show pop-up notifications. That is how fake virus warnings get onto the screen.'
        'advice.notifySites'     = 'Block them in the browser: Settings > Privacy and security > Site settings > Notifications. Never call a phone number from such a pop-up.'
        'finding.hostsRedirect'  = 'The hosts file sends website names to other addresses.'
        'advice.hostsRedirect'   = 'Check C:\Windows\System32\drivers\etc\hosts. Lines the client does not recognise can go (needs admin).'
        'finding.cleanPopup'     = 'Nothing on this PC explains the pop-up. It was most likely a scam web page, not a real virus.'
        'advice.cleanPopup'      = 'Such a page is harmless once it is closed: close the browser (Alt+F4, or Task Manager if it will not close). Never call the number on it. If the client did call: choose F2.'
        'finding.cleanCall'      = 'No remote-access program or other trace of an intruder found.'
        'advice.cleanCall'       = 'If the caller asked for bank details or codes, call the bank anyway. Quick Assist is built into Windows and leaves nothing behind once closed.'
        'finding.cleanAll'       = 'No security problems found.'
        'advice.cleanAll'        = 'Keep Windows and the browser up to date. Real companies never call about a virus.'

        # ---- fixes and undo
        'fix.heading'      = 'What next?'
        'fix.steps'        = 'Step by step: how to do it by hand'
        'fix.stepOf'       = 'Step {0} of {1}:'
        'fix.stepNext'     = 'Enter = next step, 0 = stop'
        'fix.stepLast'     = 'Enter = done'
        'fix.enterBack'    = 'Enter = back to the menu'
        'fix.note.undo'    = '(can be undone)'
        'fix.note.safe'    = '(safe, changes nothing else)'
        'fix.note.restart' = '(the program can simply be started again)'
        'fix.needsAdmin'   = '(needs admin)'
        'fix.confirm'      = '{0}? (Y/N)'
        'fix.dryRun'       = 'DRY RUN: nothing was changed.'
        'fix.done'         = 'Done.'
        'fix.failed'       = 'That did not work: {0}'
        'fix.adminHow'     = 'This needs admin. Close this window, right-click the Start button, choose Terminal (Admin), and start Housecall again.'
        'fix.checkingAgain' = 'Checking again, to see whether it worked...'
        'fix.cancelled'    = 'Nothing was changed.'
        'fix.disableTask'  = 'Disable scheduled task "{0}"'
        'fix.stopRemote'   = 'Close {0} now'
        'fix.proxyOff'     = 'Turn off the proxy'
        'fix.flushDns'     = 'Clear the DNS cache'
        'fix.renewIp'      = 'Ask the router for a new address'
        'menu.undo'        = 'Undo fixes'
        'undo.nothing'     = 'There is nothing to undo.'
        'undo.confirm'     = 'Undo {0} change(s) made in this session? (Y/N)'
        'undo.done'        = 'Undone: {0}'
        'undo.failed'      = 'Could not undo: {0}'
        'sec.taskKnown'    = 'Scheduled task "{0}" belongs to {1}, a known tool'
        'sec.taskDisabled' = 'Scheduled task "{0}" is disabled'

        # ---- step-by-step guides: steps.<finding id>, steps separated by |
        'steps.noAdapter'        = 'Right-click the Start button and choose Device Manager. | Open "Network adapters". Look for an entry with a yellow warning sign. If you see nothing, choose View > Show hidden devices. | Note the brand and model of the PC (often on a sticker underneath). | On a phone or another PC, download the network driver from the maker''s support website and copy it over on a USB stick. | Run the driver installer, restart the PC, and choose A1 again.'
        'steps.wifiDisabled'     = 'Click the network icon at the bottom right, next to the clock. | If the Wi-Fi tile is grey, click it so it turns blue. | If the Airplane mode tile is blue, click it to turn it off. | On a laptop, also try the Wi-Fi key on the keyboard (often Fn plus a key with an antenna). | Choose A1 again to check.'
        'steps.adapterOff'       = 'Open Settings (Windows key + I) and go to Network & internet. | Click Advanced network settings. | Find the adapter marked Disabled and click Enable next to it. | Choose A1 again to check.'
        'steps.wifiNotConnected' = 'Click the network icon at the bottom right, next to the clock. | Make sure Airplane mode is off. | Click the arrow next to the Wi-Fi tile to see the networks. | Choose the home network and click Connect. | Type the Wi-Fi password: it is often on a sticker on the router. | Choose A1 again to check.'
        'steps.cableUnplugged'   = 'Follow the cable from the PC to the router. | Push the plug in firmly at both ends until it clicks. The small light next to the port should start blinking. | No light? Try another port on the router. | Still nothing? Try another cable. | Choose A1 again to check.'
        'steps.noAddress'        = 'Choose the fix above to ask the router for a new address (needs admin), or carry on by hand. | Pull the power plug out of the router, and out of the modem if that is a separate box. | Wait 30 seconds, then plug it back in. | Wait about 3 minutes until the lights are steady. | Choose A1 again to check.'
        'steps.noGateway'        = 'Open Settings (Windows key + I) and go to Network & internet. | Click Wi-Fi or Ethernet, then the connection in use (for Wi-Fi: its properties). | Next to IP assignment, click Edit. | Choose Automatic (DHCP) and click Save. | Choose A1 again to check.'
        'steps.gatewayDown'      = 'Look at the router: are its lights on? | Pull the power plug out of the router, and out of the modem if that is a separate box. | Wait 30 seconds, then plug it back in. | Wait about 3 minutes until the lights are steady. | Choose A1 again. If the router stays dark, it may be broken: call the provider.'
        'steps.internetDown'     = 'Look at the router: the internet or WAN light is probably red or off. | Restart the modem and router: power off for 30 seconds, then wait 3 minutes. | On a phone with Wi-Fi off, check for an outage at the provider, for example on allestoringen.nl. | Still no internet? Call the provider: the problem is outside the house. | Choose A1 again to check.'
        'steps.dnsDown'          = 'Choose the fix above to clear the DNS cache, or carry on by hand. | Open Settings (Windows key + I) > Network & internet and click the connection in use. | Next to DNS server assignment, click Edit. | Choose Automatic (DHCP) and click Save. | Choose A1 again to check.'
        'steps.webIntercepted'   = 'Open a web browser and go to any website, for example nu.nl. | If a login or "accept the terms" page appears (hotel, library, guest Wi-Fi), fill it in. | If nothing appears, choose F3 to look for a proxy or unknown programs. | Choose A1 again to check.'
        'steps.proxy'            = 'Choose the fix above to turn the proxy off (it can be undone), or carry on by hand. | Open Settings (Windows key + I) > Network & internet > Proxy. | Under Manual proxy setup, click Edit and switch "Use a proxy server" off. | Under Automatic proxy setup, switch "Use setup script" off. | Choose F3 to look for the program that set it.'
        'steps.weakSignal'       = 'Take the laptop to the router and choose A1 again. Strong there? Then distance is the problem. | Take the router out of cupboards, off the floor, and away from metal. | If the router has two networks (2.4 and 5 GHz), use 2.4 GHz in rooms far away. | In a large house, a Wi-Fi extender or mesh point halfway helps.'
        'steps.unstable'         = 'Restart the router: power off for 30 seconds, then wait 3 minutes. | Sit closer to the router and choose A2 again. | Pause big downloads, streaming and video calls on other devices, and test again. | Still unstable? Use a network cable, or ask the provider for a new router.'
        'steps.dropsMany'        = 'Right-click the Start button and choose Device Manager. | Open Network adapters and double-click the Wi-Fi adapter. | On the Power Management tab, untick "Allow the computer to turn off this device to save power". | On the Driver tab, click Update driver > Search automatically for drivers. | Restart the router and the PC.'
        'steps.connHealthy'      = 'Close other programs and browser tabs. | Open speedtest.net on this PC and click Go. | Compare the download speed with the subscription (on the provider''s bill or website). | Much lower? Test again with a network cable. Still low: call the provider. | Only slow in the evening? Those are busy hours at the provider.'
        'steps.siteHosts'        = 'Open Notepad as administrator: type Notepad in Start, right-click it, choose Run as administrator. | Choose File > Open, set the file type to All files, and paste: C:\Windows\System32\drivers\etc\hosts | Delete the line with the site name and save. | Choose F3 to look for what put it there.'
        'steps.siteNotFound'     = 'Check the spelling of the address with the client. | Search for the name of the site in a search engine instead of typing the address. | Try it on a phone: if it fails there too, the site is down or gone.'
        'steps.siteBlocked'      = 'Try the site on a phone with Wi-Fi off. | Works there? Pause the antivirus or firewall on this PC for a moment and try again. | If that helps, add the site as an exception in that security program, and switch the protection back on.'
        'steps.siteError'        = 'Wait 15 minutes and try again. | Check on a phone whether the site gives an error there too. | Look for an outage of the site, for example on allestoringen.nl.'
        'steps.siteOk'           = 'Open the site in the browser and press Ctrl + F5 to reload it completely. | Still wrong? Try it in another browser, for example Edge. | Works there? In the first browser: Settings > Privacy > Clear browsing data (cookies and cache). | Still wrong? Switch off browser extensions one by one. | For an app: update it, or remove it and install it again.'
        'steps.remoteActive'     = 'Cut the internet: switch Wi-Fi off (network icon at the bottom right) or pull the network cable. | Choose the fix above to close the program. | Ask the client whether they know the program, and who asked them to install it. | If it was a stranger: call the bank straight away, on the number on the bank card. | Change the email and bank passwords from another device, not from this PC. | Choose F3 for a full check.'
        'steps.remoteRecent'     = 'Ask the client who installed the program, and when they last spoke to that person. | If it was a stranger: call the bank straight away, on the number on the bank card. | Remove the program: Settings > Apps, find it in the list, click the three dots next to it and choose Uninstall. | Change the email and bank passwords from another device. | Choose F2 again to check.'
        'steps.remoteOld'        = 'Ask the client whether they or their family use the program. | If nobody does: Settings > Apps, find it in the list, click the three dots next to it and choose Uninstall. | Choose F2 again to check.'
        'steps.defenderOff'      = 'Type Windows Security in Start and open it. | Click Virus & threat protection. | Is another antivirus listed that has expired? Remove it: Settings > Apps, find it in the list, three dots, Uninstall. | Under Virus & threat protection settings, click Manage settings and switch Real-time protection on. | Choose F3 again to check.'
        'steps.avOld'            = 'Type Windows Security in Start and open it. | Click Virus & threat protection. | Under Protection updates, click Check for updates. | Does that fail? Choose E1 to check Windows Update.'
        'steps.threatsFound'     = 'Type Windows Security in Start and open it. | Click Virus & threat protection > Protection history. | See what was found, and whether it says Removed or Quarantined. | Go back, click Scan options, choose Full scan and click Scan now. Let it finish.'
        'steps.suspiciousTask'   = 'Choose the fix above to disable the task (it can be switched back on). | Type Windows Security in Start and open it. | Click Virus & threat protection > Scan options, choose Microsoft Defender Offline scan and click Scan now. The PC restarts for this. | Afterwards, choose F3 again.'
        'steps.unknownTask'      = 'Ask the client whether they know the program the task "{0}" belongs to. | Search for the name "{0}" online to see which program it comes from. | Unknown and not needed? Choose the fix above to disable it (it can be switched back on).'
        'steps.notifySites'      = 'Open the browser named next to the site. | Chrome, Edge or Brave: Settings > Privacy and security > Site settings > Notifications. | Under "Allowed to send notifications", click the three dots next to each unknown site and choose Block or Remove. | Tell the client: a pop-up with a phone number is never real. Close it, and never call.'
        'steps.hostsRedirect'    = 'Open Notepad as administrator: type Notepad in Start, right-click it, choose Run as administrator. | Choose File > Open, set the file type to All files, and paste: C:\Windows\System32\drivers\etc\hosts | Delete the lines the client does not recognise and save. | Choose F3 again to check.'
        'steps.cleanPopup'       = 'Is the pop-up still on screen? Press Ctrl + Shift + Esc to open Task Manager. | Select the browser and click End task. | Open the browser again. If it offers to restore the tabs, say no. | Tell the client: such pages look scary but do nothing once closed. Never call the number.'
        'steps.cleanCall'        = 'Ask what the caller did: did they see the screen, or ask for codes or bank details? | If they asked for bank details or codes: call the bank on the number on the bank card. | Change the email password from another device. | Tell the client: banks and Microsoft never call about a virus.'
    }

    nl = @{
        'tagline'          = 'vindt en verhelpt computerproblemen, altijd met uw akkoord'
        'promise'          = 'Er verandert niets op deze pc zonder uw ja.'

        'status.admin'     = 'beheerder'
        'status.notAdmin'  = 'geen beheerder'
        'status.online'    = 'online'
        'status.offline'   = 'offline'
        'status.dryRun'    = 'PROEFDRAAI: alleen controleren, er wordt niets hersteld'

        'menu.question'    = 'Waar gaat het probleem over?'
        'menu.ai'          = 'Iets anders: beschrijf het zelf (AI-chat)'
        'menu.hintHome'    = 'Typ een letter, of ga direct naar een probleem, bijv. A1'
        'menu.back'        = 'Terug'
        'menu.language'    = 'English'
        'menu.quit'        = 'Stoppen'
        'menu.prompt'      = 'Kies'
        'menu.unknown'     = '"{0}" is geen keuze. Probeer een letter zoals A, of een code zoals A1.'

        'area.question'    = '{0}  {1}: wat is het probleem?'
        'area.ai'          = 'Geen van deze: beschrijf het zelf (AI-chat)'
        'area.hint'        = 'Typ een nummer, bijv. 1, of de hele code'

        'problem.notBuilt' = 'De controles voor dit probleem zijn nog niet gebouwd.'
        'problem.willLook' = 'Er wordt gekeken naar:'
        'pressEnter'       = 'Druk op Enter om terug te gaan'

        'ai.title'         = 'Beschrijf het probleem in uw eigen woorden'
        'ai.youTyped'      = 'U typte: {0}'
        'ai.notBuilt'      = 'De AI-chat is nog niet gebouwd. Kies voorlopig een letter uit het menu.'
        'ai.offline'       = 'Deze pc is offline, dus de AI-chat is niet bereikbaar. Het menu werkt zonder internet.'

        'goodbye'          = 'Housecall is gesloten. Er is niets achtergebleven op deze pc.'
        'goodbyeChanged'   = 'Housecall is gesloten. De {0} wijziging(en) die u goedkeurde blijven staan; verder is er niets achtergebleven.'
        'env.notWindows'   = 'Housecall werkt alleen op Windows.'
        'env.oldPowerShell' = 'Housecall heeft PowerShell 5.1 of nieuwer nodig. Deze pc heeft {0}.'

        'area.A'  = 'Internet en wifi'
        'area.B'  = 'Geluid, beeld en videobellen'
        'area.C'  = 'Printer en apparaten'
        'area.D'  = 'Traag of vastlopen'
        'area.E'  = 'Windows en updates'
        'area.F'  = 'Veiligheid en oplichting'

        'looks.A' = 'netwerkadapter, adres van de router, router, DNS, internet, proxy, wifi-signaal'
        'looks.B' = 'standaard geluidsapparaat, dempen en volume, audioservice, toegang tot camera en microfoon, schermschaal'
        'looks.C' = 'afdrukservice, vastgelopen printopdrachten, standaardprinter, USB-apparaten met fouten, Bluetooth'
        'looks.D' = 'vrije schijfruimte, programma''s die geheugen en processor gebruiken, opstartprogramma''s, recente crashes, tijd sinds herstart'
        'looks.E' = 'Windows Update-service, laatste geslaagde update, wachtende herstart'
        'looks.F' = 'programma''s voor overname op afstand zoals AnyDesk, sites die meldingen mogen sturen, Microsoft Defender, onbekende geplande taken'

        'problem.A1' = 'Helemaal geen internet'
        'problem.A2' = 'Wifi is traag of valt steeds weg'
        'problem.A3' = 'Een website of app laadt niet'
        'problem.A4' = 'E-mail verzenden of ontvangen lukt niet'
        'problem.B1' = 'Geen geluid'
        'problem.B2' = 'Microfoon of camera (videobellen)'
        'problem.B3' = 'Scherm te klein, te donker of verkeerd'
        'problem.C1' = 'De printer print niet'
        'problem.C2' = 'Muis, toetsenbord of USB-stick'
        'problem.C3' = 'Bluetooth'
        'problem.D1' = 'De hele computer is traag'
        'problem.D2' = 'Opstarten duurt heel lang'
        'problem.D3' = 'Een programma loopt vast of crasht'
        'problem.D4' = 'De schijf is vol'
        'problem.E1' = 'Update loopt vast of mislukt'
        'problem.E2' = 'Foutmelding op het scherm'
        'problem.E3' = 'Afsluiten of herstarten lukt niet'
        'problem.F1' = 'Een pop-up zegt dat ik een virus heb'
        'problem.F2' = 'Iemand belde mij en kwam in mijn computer'
        'problem.F3' = 'Volledige veiligheidscontrole'

        # ---- running a check
        'run.checking' = 'Bezig met controleren... er verandert niets op deze pc.'
        'run.found'    = 'Gevonden:'
        'run.advice'   = 'Wat te doen:'

        # ---- A: check lines
        'net.noAdapter'        = 'Geen netwerkadapter gevonden'
        'net.wifiDisabled'     = 'Wifi-adapter "{0}" staat uit'
        'net.adapterOff'       = 'Netwerkadapter "{0}" staat uit'
        'net.wifiNotConnected' = 'Wifi staat aan, maar is met geen enkel netwerk verbonden'
        'net.cableUnplugged'   = 'Geen netwerkkabel aangesloten ("{0}")'
        'net.adapterUp'        = 'Netwerkadapter "{0}" staat aan'
        'net.wifiConnected'    = 'Verbonden met wifi "{0}", signaal {1}%'
        'net.wifiConnectedNoSignal' = 'Verbonden met wifi'
        'net.cableConnected'   = 'Verbonden via een netwerkkabel'
        'net.weakSignal'       = 'Het wifi-signaal is zwak: {0}%'
        'net.proxy'            = 'Verkeer gaat via een proxy: {0}'
        'net.noAddress'        = 'Geen adres van de router ({0})'
        'net.address'          = 'Adres van de router: {0}'
        'net.addressStatic'    = 'Vast adres, met de hand ingesteld: {0}'
        'net.noGateway'        = 'Geen router (gateway) ingesteld voor deze verbinding'
        'net.gatewayOk'        = 'Router {0} antwoordt in {1} ms'
        'net.gatewayNoPing'    = 'Router {0} negeert testberichten (dat is geen probleem)'
        'net.gatewayDown'      = 'Router {0} antwoordt niet'
        'net.internetDown'     = 'Voorbij de router komt niets op internet'
        'net.internetOk'       = 'Internet bereikbaar, {0} ms'
        'net.dnsDown'          = 'Namen van websites worden niet gevonden (DNS-server {0})'
        'net.dnsOk'            = 'Namen van websites worden gevonden (DNS)'
        'net.webOk'            = 'Testpagina laadt normaal'
        'net.webIntercepted'   = 'Een inlogpagina of een ander programma vangt het webverkeer af'
        'net.webFailed'        = 'De testpagina laadt niet'
        'net.skipped'          = 'Overige controles overgeslagen'
        'net.lossOk'           = 'Routertest: alle {0} berichten kwamen terug, gemiddeld {1} ms'
        'net.loss'             = 'Routertest: {0} van de {1} berichten kwijtgeraakt'
        'net.drops'            = 'Keren dat de wifi wegviel, afgelopen 7 dagen: {0} (slaapstand en afsluiten meegeteld)'
        'net.internetWorks'    = 'Internet werkt op deze pc'
        'net.none'             = 'geen'

        # ---- A: findings, and what to do about each
        'finding.noAdapter'        = 'Windows ziet helemaal geen netwerkadapter. Het stuurprogramma ontbreekt misschien, of de adapter is kapot.'
        'advice.noAdapter'         = 'Open Apparaatbeheer en zoek een netwerkadapter met een waarschuwingsteken. Installeer het stuurprogramma van de site van de fabrikant, via een telefoon (USB-tethering) of een andere pc.'
        'finding.wifiDisabled'     = 'De wifi-adapter staat uit.'
        'advice.wifiDisabled'      = 'Zet wifi aan: Instellingen > Netwerk en internet > Wifi, of de wifitoets op het toetsenbord. Controleer ook of de vliegtuigstand uit staat.'
        'finding.adapterOff'       = 'De netwerkadapter staat uit.'
        'advice.adapterOff'        = 'Zet hem weer aan: Instellingen > Netwerk en internet > Geavanceerde netwerkinstellingen > Inschakelen.'
        'finding.wifiNotConnected' = 'Wifi staat aan, maar de pc is met geen netwerk verbonden.'
        'advice.wifiNotConnected'  = 'Controleer of de vliegtuigstand uit staat. Klik dan rechtsonder op het wifi-icoon en kies het thuisnetwerk. Het wachtwoord staat vaak op een sticker op de router.'
        'finding.cableUnplugged'   = 'Deze pc gebruikt een netwerkkabel, maar de kabel is niet aangesloten.'
        'advice.cableUnplugged'    = 'Druk de kabel aan beide kanten aan tot hij klikt. Probeer een andere poort op de router, of een andere kabel.'
        'finding.noAddress'        = 'De pc is verbonden, maar de router heeft hem geen adres gegeven.'
        'advice.noAddress'         = 'Vernieuw het adres: ipconfig /release en daarna ipconfig /renew. Helpt dat niet, herstart dan de router: 30 seconden stroom eraf, daarna 3 minuten wachten.'
        'finding.noGateway'        = 'Er is geen router ingesteld voor deze verbinding. Meestal een vast adres dat met de hand is ingesteld.'
        'advice.noGateway'         = 'Zet de verbinding terug op automatisch: Instellingen > Netwerk en internet > (de verbinding) > IP-toewijzing > Automatisch (DHCP).'
        'finding.gatewayDown'      = 'De router antwoordt niet.'
        'advice.gatewayDown'       = 'Kijk of de lampjes van de router branden. Herstart hem: 30 seconden stroom eraf, daarna 3 minuten wachten.'
        'finding.internetDown'     = 'De router werkt, maar de router zelf heeft geen internet.'
        'advice.internetDown'      = 'Herstart modem en router. Kijk op een telefoon of er een storing is bij de provider (bijv. allestoringen.nl). Controleer het internetlampje op de router.'
        'finding.dnsDown'          = 'Internet werkt, maar namen van websites worden niet gevonden (DNS).'
        'advice.dnsDown'           = 'Leeg de DNS-cache: ipconfig /flushdns. Zijn de DNS-servers met de hand ingesteld, zet ze dan terug op automatisch.'
        'finding.webIntercepted'   = 'Iets vangt het webverkeer af: een inlogpagina van de wifi (hotel, gastnetwerk) of een programma op deze pc.'
        'advice.webIntercepted'    = 'Open een browser en kijk of er een inlogpagina verschijnt. Is die er niet, kies dan F3 om naar onbekende programma''s te zoeken.'
        'finding.proxy'            = 'Er is een proxy ingesteld. Op een thuis-pc is dat meestal ongewenst, en soms adware.'
        'advice.proxy'             = 'Zet hem uit: Instellingen > Netwerk en internet > Proxy. Kies daarna F3 om naar onbekende programma''s te zoeken.'
        'finding.weakSignal'       = 'Internet werkt, maar het wifi-signaal is hier zwak.'
        'advice.weakSignal'        = 'Ga dichter bij de router zitten, zet de router niet in een kast, of plaats een wifi-versterker of mesh-punt.'
        'finding.allGood'          = 'De internetverbinding werkt op deze pc.'
        'advice.allGood'           = 'Doet een bepaalde website of app het niet, kies dan A3. Is internet traag of valt het weg, kies dan A2.'
        'finding.unstable'         = 'De verbinding met de router is onstabiel: {0}% van de testberichten raakte kwijt.'
        'advice.unstable'          = 'Herstart de router en ga er dichterbij zitten. Een netwerkkabel is stabieler dan wifi.'
        'finding.dropsMany'        = 'De wifi viel de afgelopen 7 dagen {0} keer weg, vaker dan slaapstand en afsluiten verklaren.'
        'advice.dropsMany'         = 'Werk het wifi-stuurprogramma bij, zet energiebesparing voor de wifi-adapter uit in Apparaatbeheer, en herstart de router.'
        'finding.connHealthy'      = 'De verbinding ziet er nu gezond uit. Traagheid komt waarschijnlijk door het abonnement of de provider.'
        'advice.connHealthy'       = 'Doe een snelheidstest (bijv. speedtest.net) en vergelijk die met het abonnement. Probeer het ook op een ander moment van de dag.'

        # ---- A3: one website
        'site.ask'       = 'Welke website? Bijvoorbeeld: marktplaats.nl'
        'site.invalid'   = '"{0}" lijkt geen webadres. Typ het zo: whatsapp.com'
        'site.hosts'     = 'Het hosts-bestand stuurt {0} naar {1}'
        'site.hostsOk'   = 'Geen speciale regel voor {0} in het hosts-bestand'
        'site.dnsOk'     = '{0} gevonden: {1}'
        'site.dnsFail'   = '{0} niet gevonden'
        'site.tcpOk'     = '{0} antwoordt op de beveiligde poort, {1} ms'
        'site.tcpFail'   = '{0} antwoordt niet op de beveiligde poort'
        'site.httpOk'    = '{0} stuurt een pagina (status {1})'
        'site.httpError' = '{0} antwoordt met een fout (status {1})'
        'site.httpNone'  = '{0} stuurt geen pagina'

        'finding.siteHosts'    = 'Het hosts-bestand stuurt deze site naar een ander adres: een oude instelling, of malware.'
        'advice.siteHosts'     = 'Haal de regel voor deze site weg uit C:\Windows\System32\drivers\etc\hosts (beheerder nodig) en kies daarna F3.'
        'finding.siteNotFound' = 'De naam {0} wordt niet gevonden. Misschien een typefout, of de site bestaat niet meer.'
        'advice.siteNotFound'  = 'Controleer de spelling. Probeer het op een telefoon: lukt het daar ook niet, dan ligt het aan de site.'
        'finding.siteBlocked'  = 'De site wordt gevonden, maar antwoordt niet aan deze pc.'
        'advice.siteBlocked'   = 'Probeer het op een telefoon met wifi uit. Werkt het daar wel, dan blokkeert beveiligingssoftware of een firewall op deze pc het misschien.'
        'finding.siteError'    = 'De site antwoordt met een fout ({0}). Het probleem ligt waarschijnlijk bij de site zelf.'
        'advice.siteError'     = 'Probeer het later nog eens. Kijk op een telefoon of het daar ook misgaat.'
        'finding.siteOk'       = 'De site werkt vanaf deze pc. Het probleem zit waarschijnlijk in de browser of de app.'
        'advice.siteOk'        = 'Wis de cache en cookies van deze site in de browser, probeer een andere browser, of zet browserextensies uit. Bij een app: bijwerken of opnieuw installeren.'

        # ---- F: check lines
        'sec.noRemote'         = 'Geen programma''s voor overname op afstand gevonden'
        'sec.installed'        = 'op de pc gezet op {0}'
        'sec.installedUnknown' = 'staat op de pc, datum onbekend'
        'sec.downloaded'       = 'gedownload op {0}'
        'sec.running'          = 'DRAAIT NU'
        'sec.autoStart'        = 'start mee met Windows'
        'sec.lastUsed'         = 'laatst gebruikt op {0}'
        'sec.noTasks'          = 'Geen verdachte geplande taken'
        'sec.task'             = 'Geplande taak "{0}" start: {1}'
        'sec.avUnknown'        = 'De status van de virusbescherming kon niet worden gelezen'
        'sec.avOff'            = 'Er staat geen virusbescherming aan'
        'sec.avOld'            = '{0} staat aan, maar is {1} dagen niet bijgewerkt'
        'sec.avOutdated'       = '{0} staat aan, maar is niet bijgewerkt'
        'sec.avOk'             = '{0} staat aan en is bijgewerkt'
        'sec.threats'          = 'Bedreigingen tegengehouden, afgelopen 30 dagen: {0}'
        'sec.notifyNone'       = 'Geen websites mogen pop-upmeldingen sturen'
        'sec.notifyKnown'      = 'Bekende sites mogen meldingen sturen: {0}'
        'sec.notifySite'       = '{0} mag meldingen sturen ({1}, sinds {2})'
        'sec.notifySiteNoDate' = '{0} mag meldingen sturen ({1})'
        'sec.noProxy'          = 'Geen proxy ingesteld'
        'sec.hostsOk'          = 'Het hosts-bestand is normaal'
        'sec.hostsRedirect'    = 'Het hosts-bestand stuurt {0} naam/namen door: {1}'

        # ---- F: findings, and what to do about each
        'finding.remoteActive'   = '{0} draait op dit moment. Er kan nu iemand met deze pc verbonden zijn.'
        'advice.remoteActive'    = 'Verbreek eerst het internet: wifi uit of kabel eruit. Sluit dan het programma en vraag of de klant het kent. Zo niet: verwijder het na hun ja, bel de bank, en wijzig de wachtwoorden van e-mail en bank vanaf een ander apparaat.'
        'finding.remoteRecent'   = '{0} is kort geleden op deze pc gezet ({1}). Heeft de klant dat niet zelf gedaan, dan past het bij oplichting door een nep-helpdesk.'
        'advice.remoteRecent'    = 'Vraag de klant wie het op de pc heeft gezet. Was het een onbekende: verwijder het na hun ja, bel direct de bank, en wijzig de wachtwoorden van e-mail en bank vanaf een ander apparaat.'
        'finding.remoteOld'      = '{0} staat al langer op deze pc. Waarschijnlijk bewust, maar vraag het na.'
        'advice.remoteOld'       = 'Vraag of de klant of de familie het gebruikt. Gebruikt niemand het, dan sluit verwijderen een deur.'
        'finding.defenderOff'    = 'De virusbescherming staat uit.'
        'advice.defenderOff'     = 'Zet hem aan: Windows-beveiliging > Virus- en bedreigingsbeveiliging. Is een andere virusscanner verlopen, verwijder die dan zodat Microsoft Defender het overneemt.'
        'finding.avOld'          = 'De virusbescherming staat aan, maar is niet bijgewerkt.'
        'advice.avOld'           = 'Windows-beveiliging > Virus- en bedreigingsbeveiliging > Beveiligingsupdates > Controleren op updates. Lukt dat niet, kies dan E1.'
        'finding.threatsFound'   = 'De virusbescherming heeft de afgelopen 30 dagen {0} bedreiging(en) tegengehouden.'
        'advice.threatsFound'    = 'Open Windows-beveiliging > Beveiligingsgeschiedenis om te zien wat het was, en doe een volledige scan.'
        'finding.suspiciousTask' = 'De geplande taak "{0}" start een verborgen of gedownloade opdracht. Dat is typisch voor malware.'
        'advice.suspiciousTask'  = 'Na het ja van de klant kan Housecall hem hieronder uitschakelen (kan weer worden aangezet). Doe daarna een volledige scan in Windows-beveiliging.'
        'finding.unknownTask'    = 'De geplande taak "{0}" start een script op de achtergrond. Gewone programma''s doen dat ook, maar malware ook.'
        'advice.unknownTask'     = 'Vraag of de klant hem kent. Zo niet, dan kan Housecall hem hieronder uitschakelen (kan weer worden aangezet).'
        'finding.notifySites'    = '{0} website(s) mogen pop-upmeldingen tonen. Zo komen nep-virusmeldingen op het scherm.'
        'advice.notifySites'     = 'Blokkeer ze in de browser: Instellingen > Privacy en beveiliging > Site-instellingen > Meldingen. Bel nooit een telefoonnummer uit zo''n melding.'
        'finding.hostsRedirect'  = 'Het hosts-bestand stuurt namen van websites naar andere adressen.'
        'advice.hostsRedirect'   = 'Bekijk C:\Windows\System32\drivers\etc\hosts. Regels die de klant niet kent, mogen weg (beheerder nodig).'
        'finding.cleanPopup'     = 'Niets op deze pc verklaart de pop-up. Het was hoogstwaarschijnlijk een nepwebsite, geen echt virus.'
        'advice.cleanPopup'      = 'Zo''n pagina is onschuldig zodra hij dicht is: sluit de browser (Alt+F4, of Taakbeheer als hij niet sluit). Bel nooit het nummer dat erop staat. Heeft de klant wel gebeld: kies F2.'
        'finding.cleanCall'      = 'Geen programma voor overname op afstand of ander spoor van een indringer gevonden.'
        'advice.cleanCall'       = 'Vroeg de beller om bankgegevens of codes, bel dan toch de bank. Snelle hulp (Quick Assist) zit in Windows en laat na afloop niets achter.'
        'finding.cleanAll'       = 'Geen veiligheidsproblemen gevonden.'
        'advice.cleanAll'        = 'Houd Windows en de browser bijgewerkt. Echte bedrijven bellen nooit over een virus.'

        # ---- fixes and undo
        'fix.heading'      = 'Wat nu?'
        'fix.steps'        = 'Stap voor stap: zelf oplossen'
        'fix.stepOf'       = 'Stap {0} van {1}:'
        'fix.stepNext'     = 'Enter = volgende stap, 0 = stoppen'
        'fix.stepLast'     = 'Enter = klaar'
        'fix.enterBack'    = 'Enter = terug naar het menu'
        'fix.note.undo'    = '(kan worden teruggedraaid)'
        'fix.note.safe'    = '(veilig, verandert verder niets)'
        'fix.note.restart' = '(het programma kan gewoon weer worden gestart)'
        'fix.needsAdmin'   = '(beheerder nodig)'
        'fix.confirm'      = '{0}? (J/N)'
        'fix.dryRun'       = 'PROEFDRAAI: er is niets veranderd.'
        'fix.done'         = 'Gedaan.'
        'fix.failed'       = 'Dat lukte niet: {0}'
        'fix.adminHow'     = 'Hiervoor is beheerder nodig. Sluit dit venster, klik met rechts op de Startknop, kies Terminal (beheerder), en start Housecall opnieuw.'
        'fix.checkingAgain' = 'Opnieuw controleren of het gelukt is...'
        'fix.cancelled'    = 'Er is niets veranderd.'
        'fix.disableTask'  = 'Geplande taak "{0}" uitschakelen'
        'fix.stopRemote'   = '{0} nu afsluiten'
        'fix.proxyOff'     = 'De proxy uitzetten'
        'fix.flushDns'     = 'De DNS-cache legen'
        'fix.renewIp'      = 'De router om een nieuw adres vragen'
        'menu.undo'        = 'Wijzigingen terugdraaien'
        'undo.nothing'     = 'Er is niets om terug te draaien.'
        'undo.confirm'     = '{0} wijziging(en) van deze sessie terugdraaien? (J/N)'
        'undo.done'        = 'Teruggedraaid: {0}'
        'undo.failed'      = 'Kon niet terugdraaien: {0}'
        'sec.taskKnown'    = 'Geplande taak "{0}" hoort bij {1}, een bekend programma'
        'sec.taskDisabled' = 'Geplande taak "{0}" staat uit'

        # ---- step-by-step guides: steps.<finding id>, steps separated by |
        'steps.noAdapter'        = 'Klik met rechts op de Startknop en kies Apparaatbeheer. | Open "Netwerkadapters". Zoek een regel met een geel waarschuwingsteken. Ziet u niets, kies dan Beeld > Verborgen apparaten weergeven. | Noteer merk en model van de pc (vaak op een sticker aan de onderkant). | Download op een telefoon of andere pc het netwerkstuurprogramma van de supportsite van de fabrikant en zet het op een USB-stick. | Installeer het stuurprogramma, herstart de pc, en kies opnieuw A1.'
        'steps.wifiDisabled'     = 'Klik rechtsonder op het netwerk-icoon, naast de klok. | Is de tegel Wi-Fi grijs, klik er dan op zodat hij blauw wordt. | Is de tegel Vliegtuigstand blauw, klik er dan op om hem uit te zetten. | Probeer op een laptop ook de wifitoets op het toetsenbord (vaak Fn plus een toets met een antenne). | Kies opnieuw A1 om te controleren.'
        'steps.adapterOff'       = 'Open Instellingen (Windows-toets + I) en ga naar Netwerk en internet. | Klik op Geavanceerde netwerkinstellingen. | Zoek de adapter met Uitgeschakeld en klik ernaast op Inschakelen. | Kies opnieuw A1 om te controleren.'
        'steps.wifiNotConnected' = 'Klik rechtsonder op het netwerk-icoon, naast de klok. | Controleer of Vliegtuigstand uit staat. | Klik op het pijltje naast de tegel Wi-Fi om de netwerken te zien. | Kies het thuisnetwerk en klik op Verbinding maken. | Typ het wifi-wachtwoord: dat staat vaak op een sticker op de router. | Kies opnieuw A1 om te controleren.'
        'steps.cableUnplugged'   = 'Volg de kabel van de pc naar de router. | Druk de stekker aan beide kanten stevig aan tot hij klikt. Het lampje naast de aansluiting hoort te gaan knipperen. | Geen lampje? Probeer een andere aansluiting op de router. | Nog steeds niets? Probeer een andere kabel. | Kies opnieuw A1 om te controleren.'
        'steps.noAddress'        = 'Kies hierboven de oplossing om de router om een nieuw adres te vragen (beheerder nodig), of ga met de hand verder. | Trek de stekker uit de router, en uit het modem als dat een apart kastje is. | Wacht 30 seconden en steek de stekker er weer in. | Wacht ongeveer 3 minuten tot de lampjes rustig branden. | Kies opnieuw A1 om te controleren.'
        'steps.noGateway'        = 'Open Instellingen (Windows-toets + I) en ga naar Netwerk en internet. | Klik op Wi-Fi of Ethernet, en dan op de verbinding die gebruikt wordt (bij wifi: de eigenschappen). | Klik naast IP-toewijzing op Bewerken. | Kies Automatisch (DHCP) en klik op Opslaan. | Kies opnieuw A1 om te controleren.'
        'steps.gatewayDown'      = 'Kijk naar de router: branden de lampjes? | Trek de stekker uit de router, en uit het modem als dat een apart kastje is. | Wacht 30 seconden en steek de stekker er weer in. | Wacht ongeveer 3 minuten tot de lampjes rustig branden. | Kies opnieuw A1. Blijft de router donker, dan is hij misschien kapot: bel de provider.'
        'steps.internetDown'     = 'Kijk naar de router: het internet- of WAN-lampje is waarschijnlijk rood of uit. | Herstart modem en router: 30 seconden stroom eraf, daarna 3 minuten wachten. | Kijk op een telefoon met wifi uit of er een storing is bij de provider, bijvoorbeeld op allestoringen.nl. | Nog steeds geen internet? Bel de provider: het probleem zit buiten het huis. | Kies opnieuw A1 om te controleren.'
        'steps.dnsDown'          = 'Kies hierboven de oplossing om de DNS-cache te legen, of ga met de hand verder. | Open Instellingen (Windows-toets + I) > Netwerk en internet en klik op de verbinding die gebruikt wordt. | Klik naast Toewijzing van DNS-server op Bewerken. | Kies Automatisch (DHCP) en klik op Opslaan. | Kies opnieuw A1 om te controleren.'
        'steps.webIntercepted'   = 'Open een webbrowser en ga naar een willekeurige website, bijvoorbeeld nu.nl. | Verschijnt er een inlogpagina of "voorwaarden accepteren" (hotel, bibliotheek, gastnetwerk), vul die dan in. | Verschijnt er niets, kies dan F3 om naar een proxy of onbekende programma''s te zoeken. | Kies opnieuw A1 om te controleren.'
        'steps.proxy'            = 'Kies hierboven de oplossing om de proxy uit te zetten (kan worden teruggedraaid), of ga met de hand verder. | Open Instellingen (Windows-toets + I) > Netwerk en internet > Proxy. | Klik bij Handmatige proxy-instelling op Bewerken en zet "Een proxyserver gebruiken" uit. | Zet bij Automatische proxy-instelling "Installatiescript gebruiken" uit. | Kies F3 om het programma te zoeken dat hem heeft ingesteld.'
        'steps.weakSignal'       = 'Loop met de laptop naar de router en kies opnieuw A1. Daar sterk? Dan is de afstand het probleem. | Haal de router uit kasten, van de vloer, en weg van metaal. | Heeft de router twee netwerken (2,4 en 5 GHz), gebruik dan 2,4 GHz in kamers ver weg. | In een groot huis helpt een wifi-versterker of mesh-punt halverwege.'
        'steps.unstable'         = 'Herstart de router: 30 seconden stroom eraf, daarna 3 minuten wachten. | Ga dichter bij de router zitten en kies opnieuw A2. | Zet grote downloads, streamen en videobellen op andere apparaten even stil en test opnieuw. | Nog steeds onstabiel? Gebruik een netwerkkabel, of vraag de provider om een nieuwe router.'
        'steps.dropsMany'        = 'Klik met rechts op de Startknop en kies Apparaatbeheer. | Open Netwerkadapters en dubbelklik op de wifi-adapter. | Haal op het tabblad Energiebeheer het vinkje weg bij "De computer mag dit apparaat uitschakelen om energie te besparen". | Klik op het tabblad Stuurprogramma op Stuurprogramma bijwerken > Automatisch naar stuurprogramma''s zoeken. | Herstart de router en de pc.'
        'steps.connHealthy'      = 'Sluit andere programma''s en browsertabbladen. | Open speedtest.net op deze pc en klik op Go. | Vergelijk de downloadsnelheid met het abonnement (op de rekening of de website van de provider). | Veel lager? Test opnieuw met een netwerkkabel. Nog steeds laag: bel de provider. | Alleen ''s avonds traag? Dan is het druk bij de provider.'
        'steps.siteHosts'        = 'Open Kladblok als administrator: typ Kladblok in Start, klik er met rechts op, kies Als administrator uitvoeren. | Kies Bestand > Openen, zet het bestandstype op Alle bestanden, en plak: C:\Windows\System32\drivers\etc\hosts | Verwijder de regel met de naam van de site en sla op. | Kies F3 om te zoeken wat hem daar heeft neergezet.'
        'steps.siteNotFound'     = 'Controleer samen met de klant de spelling van het adres. | Zoek de naam van de site op in een zoekmachine in plaats van het adres te typen. | Probeer het op een telefoon: lukt het daar ook niet, dan ligt de site eruit of bestaat hij niet meer.'
        'steps.siteBlocked'      = 'Probeer de site op een telefoon met wifi uit. | Werkt het daar wel? Zet de virusscanner of firewall op deze pc even op pauze en probeer het opnieuw. | Helpt dat, voeg de site dan toe als uitzondering in dat beveiligingsprogramma, en zet de beveiliging weer aan.'
        'steps.siteError'        = 'Wacht 15 minuten en probeer het opnieuw. | Kijk op een telefoon of de site daar ook een fout geeft. | Zoek naar een storing van de site, bijvoorbeeld op allestoringen.nl.'
        'steps.siteOk'           = 'Open de site in de browser en druk op Ctrl + F5 om hem helemaal opnieuw te laden. | Nog steeds mis? Probeer het in een andere browser, bijvoorbeeld Edge. | Werkt het daar wel? In de eerste browser: Instellingen > Privacy > Browsegegevens wissen (cookies en cache). | Nog steeds mis? Zet browserextensies een voor een uit. | Bij een app: werk hem bij, of verwijder hem en installeer hem opnieuw.'
        'steps.remoteActive'     = 'Verbreek het internet: zet wifi uit (netwerk-icoon rechtsonder) of trek de netwerkkabel eruit. | Kies hierboven de oplossing om het programma af te sluiten. | Vraag of de klant het programma kent, en wie vroeg om het te installeren. | Was het een onbekende: bel direct de bank, op het nummer op de bankpas. | Wijzig de wachtwoorden van e-mail en bank vanaf een ander apparaat, niet vanaf deze pc. | Kies F3 voor een volledige controle.'
        'steps.remoteRecent'     = 'Vraag de klant wie het programma op de pc heeft gezet, en wanneer ze die persoon voor het laatst spraken. | Was het een onbekende: bel direct de bank, op het nummer op de bankpas. | Verwijder het programma: Instellingen > Apps, zoek het in de lijst, klik op de drie puntjes ernaast en kies Verwijderen. | Wijzig de wachtwoorden van e-mail en bank vanaf een ander apparaat. | Kies opnieuw F2 om te controleren.'
        'steps.remoteOld'        = 'Vraag of de klant of de familie het programma gebruikt. | Gebruikt niemand het: Instellingen > Apps, zoek het in de lijst, klik op de drie puntjes ernaast en kies Verwijderen. | Kies opnieuw F2 om te controleren.'
        'steps.defenderOff'      = 'Typ Windows-beveiliging in Start en open het. | Klik op Virus- en bedreigingsbeveiliging. | Staat er een andere virusscanner die verlopen is? Verwijder die: Instellingen > Apps, zoek hem in de lijst, drie puntjes, Verwijderen. | Klik bij Instellingen voor virus- en bedreigingsbeveiliging op Instellingen beheren en zet Realtime-beveiliging aan. | Kies opnieuw F3 om te controleren.'
        'steps.avOld'            = 'Typ Windows-beveiliging in Start en open het. | Klik op Virus- en bedreigingsbeveiliging. | Klik bij Beveiligingsupdates op Controleren op updates. | Lukt dat niet? Kies E1 om Windows Update te controleren.'
        'steps.threatsFound'     = 'Typ Windows-beveiliging in Start en open het. | Klik op Virus- en bedreigingsbeveiliging > Beveiligingsgeschiedenis. | Bekijk wat er gevonden is, en of er Verwijderd of In quarantaine staat. | Ga terug, klik op Scanopties, kies Volledige scan en klik op Nu scannen. Laat hem afmaken.'
        'steps.suspiciousTask'   = 'Kies hierboven de oplossing om de taak uit te schakelen (kan weer worden aangezet). | Typ Windows-beveiliging in Start en open het. | Klik op Virus- en bedreigingsbeveiliging > Scanopties, kies Microsoft Defender Offline-scan en klik op Nu scannen. De pc start hiervoor opnieuw op. | Kies daarna opnieuw F3.'
        'steps.unknownTask'      = 'Vraag of de klant het programma kent waar de taak "{0}" bij hoort. | Zoek de naam "{0}" online op om te zien van welk programma hij is. | Onbekend en niet nodig? Kies hierboven de oplossing om hem uit te schakelen (kan weer worden aangezet).'
        'steps.notifySites'      = 'Open de browser die naast de site staat. | Chrome, Edge of Brave: Instellingen > Privacy en beveiliging > Site-instellingen > Meldingen. | Klik onder "Toegestaan om meldingen te sturen" op de drie puntjes naast elke onbekende site en kies Blokkeren of Verwijderen. | Zeg tegen de klant: een pop-up met een telefoonnummer is nooit echt. Sluit hem, en bel nooit.'
        'steps.hostsRedirect'    = 'Open Kladblok als administrator: typ Kladblok in Start, klik er met rechts op, kies Als administrator uitvoeren. | Kies Bestand > Openen, zet het bestandstype op Alle bestanden, en plak: C:\Windows\System32\drivers\etc\hosts | Verwijder de regels die de klant niet kent en sla op. | Kies opnieuw F3 om te controleren.'
        'steps.cleanPopup'       = ('Staat de pop-up nog op het scherm? Druk op Ctrl + Shift + Esc om Taakbeheer te openen. | Selecteer de browser en klik op Taak be' + [char]0xEB + 'indigen. | Open de browser opnieuw. Vraagt hij om de tabbladen terug te zetten, zeg dan nee. | Zeg tegen de klant: zulke pagina''s zien er eng uit maar doen niets zodra ze dicht zijn. Bel nooit het nummer.')
        'steps.cleanCall'        = 'Vraag wat de beller deed: keek hij mee op het scherm, of vroeg hij om codes of bankgegevens? | Vroeg hij om bankgegevens of codes: bel de bank op het nummer op de bankpas. | Wijzig het wachtwoord van de e-mail vanaf een ander apparaat. | Zeg tegen de klant: banken en Microsoft bellen nooit over een virus.'
    }
}

$script:Lang = 'en'

# T 'key' returns the sentence in the current language; extra arguments fill
# its {0}, {1}... placeholders. A key missing from Dutch falls back to English,
# and a key missing from both shows as [key] so it is spotted, not hidden.
function T {
    # Deliberately not [Parameter(Mandatory)]: that makes it an advanced
    # function, and advanced functions refuse the extra $args used below.
    param([string]$Key)
    $text = $script:Strings[$script:Lang][$Key]
    if ($null -eq $text) { $text = $script:Strings['en'][$Key] }
    if ($null -eq $text) { return "[$Key]" }
    if ($args.Count -gt 0) { return ($text -f $args) }
    $text
}

# Dutch when Windows is set to Dutch, English for everything else.
function Get-HcDefaultLanguage {
    try {
        if ((Get-UICulture).Name -like 'nl*') { return 'nl' }
    } catch { }
    'en'
}
